<?php

// Disable ACF setup in admin panel
//define( 'ACF_LITE', false );

// Meta Panel Configuration
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_post-ingress',
		'title' => 'Ingress',
		'fields' => array (
			array (
				'key' => 'field_5c20a83ab64bb',
				'label' => 'Post Ingress',
				'name' => 'post_ingress',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'meny-modal',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'offers',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contact-form',
		'title' => 'Contact Form',
		'fields' => array (
			array (
				'key' => 'field_5627b993f5e5e',
				'label' => 'Form Shortcode',
				'name' => 'contact_form_shortcode',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '[contact-form-7 id="XXX" title="XXX"]',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contact-info',
		'title' => 'Contact Info',
		'fields' => array (
			array (
				'key' => 'field_5627b6a7899ad',
				'label' => 'Short Message',
				'name' => 'contact_info_msg',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56277c7d6920b',
				'label' => 'Email Address',
				'name' => 'contact_email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => 'admin@example.com',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_56277cf66920c',
				'label' => 'Phone Number',
				'name' => 'contact_phone_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '+00 123 456 7890',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56277d466920d',
				'label' => 'Address',
				'name' => 'contact_address',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_hero-header',
		'title' => 'Hero Header',
		'fields' => array (
			array (
				'key' => 'field_5626b57c5b2e6',
				'label' => 'Title',
				'name' => 'hero_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5626b5955b2e7',
				'label' => 'Subtitle',
				'name' => 'hero_subtitle',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5626b5a05b2e8',
				'label' => 'Hero Image',
				'name' => 'hero_bg_img',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_5626b5c95b2e9',
				'label' => 'Hero Height',
				'name' => 'hero_height',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'small' => 'Small',
					'medium' => 'Medium',
					'big' => 'Big',
					'full' => 'Full',
				),
				'default_value' => 'small',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5626b6095b2ea',
				'label' => 'Additional Options',
				'name' => 'hero_additional_options',
				'type' => 'checkbox',
				'choices' => array (
					'is_hero' => 'Enable Hero Header',
				),
				'default_value' => '',
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'meny-modal',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'offers',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-details',
		'title' => 'Portfolio Details',
		'fields' => array (
			array (
				'key' => 'field_5627c76e06991',
				'label' => 'Portfolio Category',
				'name' => 'portfolio_category',
				'type' => 'taxonomy',
				'taxonomy' => 'portfolio_category',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5627c7e2ca2cd',
				'label' => 'Portfolio Columns',
				'name' => 'portfolio_columns',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					1 => 'One Column',
					2 => 'Two Columns',
					3 => 'Three Columns',
					4 => 'Four Columns',
					5 => 'Five Columns',
					6 => 'Six Columns',
				),
				'default_value' => 3,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5627c850cfe23',
				'label' => 'Additional Options',
				'name' => 'portfolio_additional_options',
				'type' => 'checkbox',
				'choices' => array (
					'is_filtration' => 'Enable Filteration',
					'is_masonry' => 'Enable Masonry',
				),
				'default_value' => 'is_filtration
	is_masonry',
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'archive-portfolio.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-ornes.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-glomfjord.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-stott.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-gotomeloy.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_project-details',
		'title' => 'Project Details',
		'fields' => array (
			array (
				'key' => 'field_5627e2fd3d55c',
				'label' => 'Portfolio Page',
				'name' => 'portfolio_page',
				'type' => 'page_link',
				'required' => 1,
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5627f51b74d37',
				'label' => 'Custom URL',
				'name' => 'project_custom_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://www.example.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5627dc2e2c2cf',
				'label' => 'Thumbnail Dimension',
				'name' => 'project_thumb_dimension',
				'type' => 'checkbox',
				'choices' => array (
					'w2' => '2x Thumbnail Width',
					'h2' => '2x Thumbnail Height',
				),
				'default_value' => '',
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c6276ae9a29e',
	'title' => 'Hero Carousel',
	'fields' => array(
		array(
			'key' => 'field_5c6276f509ff0',
			'label' => 'Enable Carousel',
			'name' => 'enable_carousel',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'is_carousel' => 'Enable Carousel Hero',
			),
			'allow_custom' => 0,
			'default_value' => array(
				0 => 'false',
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'array',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5c64008594bb7',
			'label' => 'Enable slides',
			'name' => 'enable_slides',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'slide_1' => 'Slide 1 *',
				'slide_2' => 'Slide 2',
				'slide_3' => 'Slide 3',
				'slide_4' => 'Slide 4',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'array',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5c63d7fd47483',
			'label' => 'Slide 1',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c64008594bb7',
						'operator' => '==',
						'value' => 'slide_1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c63d95ec89ce',
			'label' => 'Image',
			'name' => 'slide_1_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5c62787e09ff3',
			'label' => 'Custom Title',
			'name' => 'slide_1_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c62791509ff5',
			'label' => 'Custom Subtitle',
			'name' => 'slide_1_subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c62793309ff6',
			'label' => 'Button 1 Class',
			'name' => 'slide_1_button_1_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'btn-success',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6bcb44a9321',
			'label' => 'Button 1 ID',
			'name' => 'slide_1_button_1_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6279a409ff7',
			'label' => 'Button 1 Ikon',
			'name' => 'slide_1_button_1_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> calendar-check',
			'default_value' => 'fas fa-calendar-check',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c6279f409ff8',
			'label' => 'Button 1 Tekst',
			'name' => 'slide_1_button_1_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Book nå',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c627a1709ff9',
			'label' => 'Button 1 URL',
			'name' => 'slide_1_button_1_url',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5c6beed4ebdb0',
			'label' => 'Button 1 Fancybox',
			'name' => 'slide_1_button_1_fancybox',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c627a8b09ffa',
			'label' => 'Button 2 Class',
			'name' => 'slide_1_button_2_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'btn-info',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6bcb5fa9322',
			'label' => 'Button 2 ID',
			'name' => 'slide_1_button_2_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c627a9709ffb',
			'label' => 'Button 2 Ikon',
			'name' => 'slide_1_button_2_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> play',
			'default_value' => 'fas fa-play',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c627aae09ffc',
			'label' => 'Button 2 Tekst',
			'name' => 'slide_1_button_2_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Se vår video',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c627ac009ffd',
			'label' => 'Button 2 URL',
			'name' => 'slide_1_button_2_url',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5c6beefdebdb1',
			'label' => 'Button 2 Fancybox',
			'name' => 'slide_1_button_2_fancybox',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c63d84047485',
			'label' => 'Slide 2',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c64008594bb7',
						'operator' => '==',
						'value' => 'slide_2',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c6277b009ff1',
			'label' => 'Image',
			'name' => 'slide_2_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5c63d984c89d4',
			'label' => 'Custom Title',
			'name' => 'slide_2_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63da1fc89d8',
			'label' => 'Custom Subtitle',
			'name' => 'slide_2_subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f677c0da3',
			'label' => 'Button 1 Class',
			'name' => 'slide_2_button_1_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'btn-success',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6bcba2a9323',
			'label' => 'Button 1 ID',
			'name' => 'slide_2_button_1_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f75ac0dac',
			'label' => 'Button 1 Ikon',
			'name' => 'slide_2_button_1_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> calendar-check',
			'default_value' => 'fas fa-calendar-check',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c63fc4dc0db0',
			'label' => 'Button 1 Tekst',
			'name' => 'slide_2_button_1_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Book nå',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63fc64c0db1',
			'label' => 'Button 1 URL',
			'name' => 'slide_2_button_1_url',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5c6bef34ebdb2',
			'label' => 'Button 1 Fancybox',
			'name' => 'slide_2_button_1_fancybox',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c63f67cc0da5',
			'label' => 'Button 2 Class',
			'name' => 'slide_2_button_2_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'btn-info',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6bcbbda9324',
			'label' => 'Button 2 ID',
			'name' => 'slide_2_button_2_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f7bac0dad',
			'label' => 'Button 2 Ikon',
			'name' => 'slide_2_button_2_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> play',
			'default_value' => 'fas fa-play',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c63fcf1c0db2',
			'label' => 'Button 2 Tekst',
			'name' => 'slide_2_button_2_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Se vår video',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63fcfac0db3',
			'label' => 'Button 2 URL',
			'name' => 'slide_2_button_2_url',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5c6bef49ebdb3',
			'label' => 'Button 2 Fancybox',
			'name' => 'slide_2_button_2_fancybox',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c63d82647484',
			'label' => 'Slide 3',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c64008594bb7',
						'operator' => '==',
						'value' => 'slide_3',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c63d96bc89cf',
			'label' => 'Image',
			'name' => 'slide_3_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5c63d983c89d3',
			'label' => 'Custom Title',
			'name' => 'slide_3_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63da1ec89d7',
			'label' => 'Custom Subtitle',
			'name' => 'slide_3_subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f67bc0da4',
			'label' => 'Button 1 Class',
			'name' => 'slide_3_button_1_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'btn-success',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6bcbe6a9325',
			'label' => 'Button 1 ID',
			'name' => 'slide_3_button_1_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f759c0dab',
			'label' => 'Button 1 Ikon',
			'name' => 'slide_3_button_1_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> calendar-check',
			'default_value' => 'fas fa-calendar-check',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c63fd42c0db4',
			'label' => 'Button 1 Tekst',
			'name' => 'slide_3_button_1_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Book nå',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63fd4ac0db5',
			'label' => 'Button 1 URL',
			'name' => 'slide_3_button_1_url',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5c6bef6eebdb4',
			'label' => 'Button 1 Fancybox',
			'name' => 'slide_3_button_1_fancybox',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c63f6f0c0da9',
			'label' => 'Button 2 Class',
			'name' => 'slide_3_button_2_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'btn-info',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6bcc0ca9326',
			'label' => 'Button 2 ID',
			'name' => 'slide_3_button_2_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f7c7c0dae',
			'label' => 'Button 2 Ikon',
			'name' => 'slide_3_button_2_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> play',
			'default_value' => 'fas fa-play',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c63fda4c0db6',
			'label' => 'Button 2 Tekst',
			'name' => 'slide_3_button_2_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Se vår video',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63fdb7c0db7',
			'label' => 'Button 2 URL',
			'name' => 'slide_3_button_2_url',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5c6bef81ebdb5',
			'label' => 'Button 2 Fancybox',
			'name' => 'slide_3_button_2_fancybox',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c63d9a5c89d5',
			'label' => 'Slide 4',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c64008594bb7',
						'operator' => '==',
						'value' => 'slide_4',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c63d974c89d0',
			'label' => 'Image',
			'name' => 'slide_4_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5c63d980c89d1',
			'label' => 'Custom Title',
			'name' => 'slide_4_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63da1dc89d6',
			'label' => 'Custom Subtitle',
			'name' => 'slide_4_subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f6cfc0da8',
			'label' => 'Button 1 Class',
			'name' => 'slide_4_button_1_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'btn-success',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6bcc2ea9327',
			'label' => 'Button 1 ID',
			'name' => 'slide_4_button_1_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f754c0daa',
			'label' => 'Button 1 Ikon',
			'name' => 'slide_4_button_1_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> calendar-check',
			'default_value' => 'fas fa-calendar-check',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c63fe0cc0db8',
			'label' => 'Button 1 Tekst',
			'name' => 'slide_4_button_1_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Book nå',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63fe1ec0db9',
			'label' => 'Button 1 URL',
			'name' => 'slide_5_button_1_url',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5c6bef92ebdb6',
			'label' => 'Button 1 Fancybox',
			'name' => 'slide_5_button_1_fancybox',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c63f6b9c0da7',
			'label' => 'Button 2 Class',
			'name' => 'slide_4_button_2_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'btn-info',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6bcc45a9328',
			'label' => 'Button 2 ID',
			'name' => 'slide_4_button_2_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63f7d5c0daf',
			'label' => 'Button 2 Ikon',
			'name' => 'slide_4_button_2_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> play',
			'default_value' => 'fas fa-play',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c63fe2dc0dba',
			'label' => 'Button 2 Tekst',
			'name' => 'slide_4_button_2_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Se vår video',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63fe3fc0dbb',
			'label' => 'Button 2 URL',
			'name' => 'slide_4_button_2_url',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5c6befa0ebdb7',
			'label' => 'Button 2 Fancybox',
			'name' => 'slide_4_button_2_fancybox',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-stott.php',
			),
		),
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-ornes.php',
			),
		),
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-gotomeloy.php',
			),
		),
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-glomfjord.php',
			),
		),
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'archive-portfolio.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c2f4ee0195d8',
	'title' => 'Ikoner',
	'fields' => array(
		array(
			'key' => 'field_5c2f501e7da67',
			'label' => 'Ikoner',
			'name' => 'ikon_enable',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c2f4ef87da63',
			'label' => 'Aktiv',
			'name' => 'ikon_1',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c2f507e7da68',
			'label' => 'Ikon 1 Ikon',
			'name' => 'ikon_1_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> star',
			'default_value' => 'fas fa-star',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c2f4fe57da66',
			'label' => 'Ikon 1 Tittel',
			'name' => 'ikon_1_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Erfaring:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d086bc2779',
			'label' => 'Ikon 1 Tekst',
			'name' => 'ikon_1_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f75f83dd0',
			'label' => 'Aktiv',
			'name' => 'ikon_2',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32fbba50d2d',
			'label' => 'Ikon 2 Ikon',
			'name' => 'ikon_2_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> shower',
			'default_value' => 'fas fa-clock',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32fc3d50d2e',
			'label' => 'Ikon 2 Tittel',
			'name' => 'ikon_2_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Varighet:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d08cec277a',
			'label' => 'Ikon 2 Tekst',
			'name' => 'ikon_2_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f76d83dd1',
			'label' => 'Aktiv',
			'name' => 'ikon_3',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32fd7e228eb',
			'label' => 'Ikon 3 Ikon',
			'name' => 'ikon_3_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> user-friends',
			'default_value' => 'fas fa-users',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32fdad228ec',
			'label' => 'Ikon 3 Tittel',
			'name' => 'ikon_3_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Deltakere:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d0910c277b',
			'label' => 'Ikon 3 Tekst',
			'name' => 'ikon_3_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f7d483dd2',
			'label' => 'Aktiv',
			'name' => 'ikon_4',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32fdda228ed',
			'label' => 'Ikon 4 Ikon',
			'name' => 'ikon_4_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> user-friends',
			'default_value' => 'fas fa-user-friends',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32fe01228ee',
			'label' => 'Ikon 4 Tittel',
			'name' => 'ikon_4_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Dobbeltrom:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d094ec277c',
			'label' => 'Ikon 4 Tekst',
			'name' => 'ikon_4_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f7fc83dd3',
			'label' => 'Aktiv',
			'name' => 'ikon_5',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32feaaf2a06',
			'label' => 'Ikon 5 Ikon',
			'name' => 'ikon_5_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> shower',
			'default_value' => 'fas fa-calendar',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32febcf2a07',
			'label' => 'Ikon 5 Tittel',
			'name' => 'ikon_5_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Dato:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d097bc277d',
			'label' => 'Ikon 5 Tekst',
			'name' => 'ikon_5_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f80f83dd4',
			'label' => 'Aktiv',
			'name' => 'ikon_6',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32fed5f2a08',
			'label' => 'Ikon 6 Ikon',
			'name' => 'ikon_6_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> shower',
			'default_value' => 'fas fa-map-pin',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32fef2f2a09',
			'label' => 'Ikon 6 Tittel',
			'name' => 'ikon_6_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Oppmøte:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d09bcc277e',
			'label' => 'Ikon 6 Tekst',
			'name' => 'ikon_6_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f82283dd5',
			'label' => 'Aktiv',
			'name' => 'ikon_7',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32ff0df2a0a',
			'label' => 'Ikon 7 Ikon',
			'name' => 'ikon_7_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> shower',
			'default_value' => 'fas fa-compass',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32ff20f2a0b',
			'label' => 'Ikon 7 Tittel',
			'name' => 'ikon_7_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Hvor:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d09e2c277f',
			'label' => 'Ikon 7 Tekst',
			'name' => 'ikon_7_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f82e83dd6',
			'label' => 'Aktiv',
			'name' => 'ikon_8',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32ff41f2a0d',
			'label' => 'Ikon 8 Ikon',
			'name' => 'ikon_8_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> shower',
			'default_value' => 'fas fa-credit-card',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32ff32f2a0c',
			'label' => 'Ikon 8 Tittel',
			'name' => 'ikon_8_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Pris:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d0a07c2780',
			'label' => 'Ikon 8 Tekst',
			'name' => 'ikon_8_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f83783dd7',
			'label' => 'Aktiv',
			'name' => 'ikon_9',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32ff5df2a0f',
			'label' => 'Ikon 9 Ikon',
			'name' => 'ikon_9_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> shower',
			'default_value' => 'fas fa-utensils',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32ff71f2a10',
			'label' => 'Ikon 9 Tittel',
			'name' => 'ikon_9_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Frokost:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d0a30c2781',
			'label' => 'Ikon 9 Tekst',
			'name' => 'ikon_9_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c32f8e583dd8',
			'label' => 'Aktiv',
			'name' => 'ikon_10',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c32ff87f2a11',
			'label' => 'Ikon 10 Ikon',
			'name' => 'ikon_10_ikon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '<i class="fas"></i> shower',
			'default_value' => 'fas fa-shower',
			'save_format' => 'class',
			'allow_null' => 0,
			'show_preview' => 0,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5c32ff9af2a12',
			'label' => 'Ikon 10 Tittel',
			'name' => 'ikon_10_tittel',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Dusj:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c6d0a52c2782',
			'label' => 'Ikon 10 Tekst',
			'name' => 'ikon_10_tekst',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f501e7da67',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'offers',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'meny-modal',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;